language: node_js
node_js:
- stable
deploy:
  api_key:
    secure: qALqcu4iDUEZAPICCg/J8h2fRXZ46+k30g8LmGDDqnubhEmmsBOt/SnQfYeE7FxWD8WzD7vfZ6xUnU03pz2d22MTS2aJ7zVNlaV5LUbU9Mvef+k5/aN321HYCuoautc88lLN7H22zFtQFVBM0f1B9Lr2ZVvxeJHajyjM1S6Q2tADxhMlpUGsMWc/Zfd5/JB9l96QgTuA6WJZA/lnQQ8Vig6NhGOf9j65Mx5vud2xdFDUTiCCqdkEFJhWWONAlyX7GmFelLw9d6JgHg0XXHXYjiU41MIDJbL28nkLBB1mkYhULhrwjzrC9uMZCcUsvgQ1nhSwMZ+ft4Umu9f4444e/c9Lg3fgBK+E0W+7hg3GGuvdlvFqoEdJ+1+rydwAnaRT44q2qe5DRiICdS/+NM2/wC92AmXciOzFQbNy4SlPdU1FntCR37paSxyC/PjT0g7hpouaZT66gCKp52gwvng05N30zBvi3ZcnTXGzwI9O43CtIX8Om8p/+X80C3f5DpmgHo+5+0awcPEocLy4NBaOahb/MJkL3SAFNnhgUlGGo/65GsWlgiPzIrWYpch8WGh7uXzQq2KPjamZQQsEHkmSVGc28PK3UPjS4bhDsTxxYs9B8O7ur51GrJ/VRClu4tz+okc7q9uTavN7aRIcJ9HlH6w/Y+AESudl6xGuTfd2Suw=
  provider: heroku
  strategy: api
  on:
    all_branches: true
  app:
    master: undp-ghg-staging
