language: node_js
node_js:
- stable
deploy:
  api_key:
    secure: pZHuxWu7ypDTCSYhl/jrq46xbmrL7Kdx6xgmEhFVdjqSQEWRcibbfnaDUm5fdiDbYkmK8VcGyrI5yWVh2NfX9UVE2iZzH3gknzNEk7roQhoXpNoo3EdrSMIxbbejaGSdx1UDQ2KDEZ+6iWIo2fi4bMfDFdJSVsv8Sg+SsBEArF4nCTrTxBRxBcjGbrIbOK/W3ChjkGUISfTdOafAbc2IGQhza2wlYaVorJMePmASV6YZSlYAReCO5pExLSvgwp2f7H1YaGFGb6LBugI9JockWFvWclPV5V+5ANFnzEb6L0VjcvYFr8k7Zb9nKMa70PkyY9g02ps90oYJdbNfytgGE+upA6B/JfCsNqMa8jpd7KbtS22FINSSN4olc1v37wkWla1I7SgxmTYq2cpClrxUp6uboi4M4tiGQHa18e4qrBG2V7dXJiJ1Dyli6K0QyHevg2PaeL9iaWvUtKRTShACmKMiFs1juU45Ds7hZhY9IXeBlESx0vdPxzEWnNj4qFx/k+IBfSHFQn1rl4pgMvtoTYgV6PDa60TFg5iQvf+bpuDXZcs6Wzc6E1A9mekNiS/n5kpLwT25Z4iRci15FkKwtopvGhKU5co1yVLum6ow/YP6fdIXc9rBiXYIdikOIllKCWPCOIcLZ0kw31mVfcJOKncfNbnfJnF1LWdsO0lcguI=
  provider: heroku
  strategy: api
  on:
    all_branches: false
  app:
    master: undp-ghg-staging
